name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *" 
  workflow_dispatch: 

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar animação do Snake Game
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Commit e push
        uses: EndBug/add-and-commit@v9
        with:
          message: "Atualizando Snake Game"
          add: "dist/github-snake.svg dist/github-snake-dark.svg"
